services:
  app:
    build: .
    volumes:
      - ./app:/app
    command: make dev
  
    
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - app
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: